package fuchsia:platform@0.1.0;

/// Base platform world with common imports for all components.
/// Note: HTTP support (wasi:http/outgoing-handler) will be added later
/// once WASI integration is complete.
world platform {
  import fuchsia:kv/kv@0.1.0;
  import fuchsia:config/config@0.1.0;
  import fuchsia:log/log@0.1.0;
}

/// World for task components.
/// Tasks execute work within a workflow node.
world task-component {
  include platform;
  export fuchsia:task/task@0.1.0;
}
